services:
  warframe-tools:
    build:
      context: .
      dockerfile: dockerfile
    image: warframe-tools:latest
    ports:
      - "127.0.0.1:5000:5000"
    # volumes:
    #   - ./src/data:/app/src/data
    restart: unless-stopped
  selenium:
    image: selenium/standalone-chromium:latest
    container_name: selenium
    ports:
      - "127.0.0.1:4444:4444"
    restart: unless-stopped